"""
Generate supabase/migrations/20260510000028_seed_articles.sql
Uses 2 base article templates × repeated variations = 15+ articles.
Run: python scripts/generate_article_seed.py
"""

import uuid
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "supabase", "migrations", "20260510000028_seed_articles.sql")

# 8 image slugs generated by generate_article_assets.py
IMAGES = [
    "article-solo-leveling",
    "article-anime-adaptation",
    "article-industry-news",
    "article-hiatus-return",
    "article-recommendations",
    "article-axed-series",
    "article-editorial-opinion",
    "article-manhwa-market",
]

def variants_json(slug):
    sizes = [400, 800, 1200]
    parts = []
    for w in sizes:
        h = w * 9 // 16
        url = f"/images/articles/{slug}-{w}w.webp"
        parts.append(
            f'{{"width":{w},"format":"webp","url":"{url}","size":{w*h//4}}}'
        )
    return "[" + ",".join(parts) + "]"

ARTICLES = [
    {
        "slug": "solo-leveling-completed-10-years",
        "title": "Solo Leveling Officially Completes After 10 Years",
        "subtitle": "The manhwa that redefined the isekai genre has reached its final chapter",
        "excerpt": "After a decade-long run, Chugong's landmark manhwa Solo Leveling concludes, leaving a permanent mark on the global manhwa industry.",
        "body": "## The End of an Era\n\nSolo Leveling has officially concluded after ten remarkable years. What began as a web novel adaptation became the most-read manhwa globally, fundamentally reshaping reader expectations for the medium.\n\n## Legacy\n\nThe series introduced the iconic 'system' mechanic that dozens of titles have since emulated. Its anime adaptation by A-1 Pictures introduced millions of new readers to the manhwa format.\n\n## What's Next\n\nAuthor Chugong has hinted at a new project, though no details have been released.",
        "category_slug": "release-announcements",
        "tags": ["solo-leveling", "manhwa", "completed"],
        "image_slug": "article-solo-leveling",
        "dominant_color": "#12082A",
        "publish_date": "2026-01-15T09:00:00Z",
        "reading_time": 4,
        "featured": True,
        "word_count": 320,
    },
    {
        "slug": "overgeared-anime-adaptation-announced",
        "title": "Overgeared Gets Full Anime Adaptation",
        "subtitle": "The beloved game-world manhwa is heading to animation",
        "excerpt": "Studio MAPPA confirms a full anime adaptation of Overgeared, one of the longest-running and most beloved game-world manhwa series.",
        "body": "## Official Announcement\n\nMAPPA has officially confirmed an anime adaptation of Park Saenal's Overgeared. The series, which follows legendary blacksmith Grid in a virtual reality MMORPG, has accumulated over 1,500 chapters.\n\n## Production Details\n\nThe first season will adapt the early Reidan arc. A release window of late 2026 has been announced.\n\n## Community Reaction\n\nFans have expressed excitement and some apprehension given the sheer volume of source material that needs to be adapted.",
        "category_slug": "release-announcements",
        "tags": ["overgeared", "anime", "adaptation"],
        "image_slug": "article-anime-adaptation",
        "dominant_color": "#060E28",
        "publish_date": "2026-02-01T10:00:00Z",
        "reading_time": 3,
        "featured": True,
        "word_count": 260,
    },
]

# Variations to expand the 2 base articles into 15+ unique entries
VARIATIONS = [
    ("Tower of God Season 3 Release Date Confirmed", "release-announcements", "article-industry-news", "#1C0808", "2026-01-20T08:00:00Z", False, "tower-of-god"),
    ("The Beginning After the End Manga Adaptation Details", "release-announcements", "article-anime-adaptation", "#060E28", "2026-01-25T09:00:00Z", False, "tbate"),
    ("Reaper of the Drifting Moon Enters Final Arc", "hiatus-news", "article-hiatus-return", "#061818", "2026-02-03T10:00:00Z", False, "reaper"),
    ("Omniscient Reader's Viewpoint Drama Announced", "release-announcements", "article-industry-news", "#1C0808", "2026-02-10T09:00:00Z", False, "orv"),
    ("Why Manhwa is Outselling Manga in 2026", "industry-commentary", "article-manhwa-market", "#080E1C", "2026-02-14T11:00:00Z", False, "manhwa-market"),
    ("Nano Machine Gets Anime Green Light", "release-announcements", "article-anime-adaptation", "#060E28", "2026-02-18T10:00:00Z", False, "nano-machine"),
    ("Return of the Mount Hua Sect Hiatus Update", "hiatus-news", "article-hiatus-return", "#061818", "2026-02-22T09:00:00Z", False, "mount-hua"),
    ("Top 10 Manhwa to Read in 2026", "recommendations", "article-recommendations", "#100820", "2026-03-01T08:00:00Z", False, "top-10"),
    ("The Rise of Regression Fantasy in Korean Webtoons", "editorials", "article-editorial-opinion", "#0E0A1E", "2026-03-05T10:00:00Z", False, "regression-fantasy"),
    ("Sword Bitten Axed After Low Engagement", "axed-series", "article-axed-series", "#140606", "2026-03-10T09:00:00Z", False, "sword-bitten"),
    ("Kakao Webtoon Announces Global Expansion", "industry-commentary", "article-manhwa-market", "#080E1C", "2026-03-15T11:00:00Z", False, "kakao"),
    ("Best New Manhwa Releases: March 2026", "recommendations", "article-recommendations", "#100820", "2026-03-20T08:00:00Z", False, "march-picks"),
    ("Murim Login Season 2 Confirmed", "release-announcements", "article-anime-adaptation", "#060E28", "2026-03-25T09:00:00Z", False, "murim-login"),
]

def make_slug(title_tag, i):
    return f"{title_tag}-{i+1}" if i > 0 else title_tag

lines = [
    "-- ============================================================",
    "-- Migration: 028 — Seed dummy articles (15 entries)",
    "-- Generated by scripts/generate_article_seed.py",
    "-- ============================================================",
    "",
    "DO $$ DECLARE",
]

# Declare category ID variables
cat_slugs = set(a["category_slug"] for a in ARTICLES)
for v in VARIATIONS:
    cat_slugs.add(v[1])
for cs in cat_slugs:
    var = cs.replace("-", "_")
    lines.append(f"  v_cat_{var} UUID;")

# Declare tag ID variables
all_tags = set()
for a in ARTICLES:
    for t in a["tags"]:
        all_tags.add(t)
for v in VARIATIONS:
    all_tags.add(v[6])
for t in all_tags:
    var = t.replace("-", "_")
    lines.append(f"  v_tag_{var} UUID;")

lines += [
    "BEGIN",
    "",
    "  -- Fetch category IDs",
]
for cs in cat_slugs:
    var = cs.replace("-", "_")
    lines.append(f"  SELECT id INTO v_cat_{var} FROM article_categories WHERE slug = '{cs}';")

lines += ["", "  -- Insert tags (idempotent)"]
tag_names = {
    "solo-leveling": "Solo Leveling", "manhwa": "Manhwa", "completed": "Completed",
    "overgeared": "Overgeared", "anime": "Anime", "adaptation": "Adaptation",
    "tower-of-god": "Tower of God", "tbate": "TBATE", "reaper": "Reaper of the Drifting Moon",
    "orv": "Omniscient Reader", "manhwa-market": "Market", "nano-machine": "Nano Machine",
    "mount-hua": "Return of Mount Hua", "top-10": "Top 10", "regression-fantasy": "Regression Fantasy",
    "sword-bitten": "Axed", "kakao": "Kakao Webtoon", "march-picks": "Monthly Picks",
    "murim-login": "Murim Login",
}
for t in all_tags:
    name = tag_names.get(t, t.replace("-", " ").title())
    var = t.replace("-", "_")
    lines.append(f"  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), '{name}', '{t}') ON CONFLICT (slug) DO NOTHING;")
    lines.append(f"  SELECT id INTO v_tag_{var} FROM article_tags WHERE slug = '{t}';")

# Insert the 2 base articles
lines += ["", "  -- Insert base articles and media assets"]
article_ids = []
for a in ARTICLES:
    aid = str(uuid.uuid4())
    mid = str(uuid.uuid4())
    article_ids.append((aid, a))
    img = a["image_slug"]
    cat_var = a["category_slug"].replace("-", "_")
    variants = variants_json(img)
    lines.append(f"""
  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('{mid}', '{img}', 'article-image', md5('{img}'), 1200, 675, 1.7778, 'image/webp', '{a["dominant_color"]}', '', '{variants}', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '{aid}', '{a["slug"]}', $art${a["title"]}$art$, $art${a["subtitle"]}$art$,
    $art${a["body"]}$art$, $art${a["excerpt"]}$art$,
    (SELECT id FROM media_assets WHERE slug = '{img}' AND asset_type = 'article-image' LIMIT 1),
    v_cat_{cat_var}, 'published', '{a["publish_date"]}', {'TRUE' if a["featured"] else 'FALSE'}, {a["reading_time"]}, {a["word_count"]}
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = '{a["slug"]}');""")
    for tag in a["tags"]:
        tvar = tag.replace("-", "_")
        lines.append(f"  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('{aid}', v_tag_{tvar}) ON CONFLICT DO NOTHING;")

# Insert variation articles
lines += ["", "  -- Insert variation articles"]
for i, v in enumerate(VARIATIONS):
    title, cat_slug, img_slug, dom_color, pub_date, featured, tag_key = v
    aid = str(uuid.uuid4())
    mid = str(uuid.uuid4())
    slug = f"{tag_key}-news-{i+1}"
    cat_var = cat_slug.replace("-", "_")
    tag_var = tag_key.replace("-", "_")
    excerpt = f"Latest update on {title.lower()} — stay tuned for more details as they emerge from the source."
    body = f"## {title}\n\nThis is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.\n\n## Background\n\nThe community has been closely following this story. Reactions have been mixed but largely enthusiastic.\n\n## What This Means\n\nFor fans of the genre, this represents a significant development in an already exciting year for manhwa."
    variants = variants_json(img_slug)
    word_count = 60
    reading_time = 2
    lines.append(f"""
  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('{mid}', '{img_slug}-v{i}', 'article-image', md5('{img_slug}-v{i}'), 1200, 675, 1.7778, 'image/webp', '{dom_color}', '', '{variants}', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '{aid}', '{slug}', $art${title}$art$, 'Latest update from the manhwa world',
    $art${body}$art$, $art${excerpt}$art$,
    (SELECT id FROM media_assets WHERE slug = '{img_slug}-v{i}' AND asset_type = 'article-image' LIMIT 1),
    v_cat_{cat_var}, 'published', '{pub_date}', FALSE, {reading_time}, {word_count}
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = '{slug}');""")
    lines.append(f"  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('{aid}', v_tag_{tag_var}) ON CONFLICT DO NOTHING;")

lines += ["", "END $$;", ""]

sql = "\n".join(lines)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(sql)

print(f"Written: {OUT}")
print(f"Total articles: {len(ARTICLES) + len(VARIATIONS)}")
