-- ============================================================
-- Migration: 028 — Seed dummy articles (15 entries)
-- Generated by scripts/generate_article_seed.py
-- ============================================================

DO $$ DECLARE
  v_cat_axed_series UUID;
  v_cat_industry_commentary UUID;
  v_cat_editorials UUID;
  v_cat_recommendations UUID;
  v_cat_release_announcements UUID;
  v_cat_hiatus_news UUID;
  v_tag_tower_of_god UUID;
  v_tag_kakao UUID;
  v_tag_murim_login UUID;
  v_tag_regression_fantasy UUID;
  v_tag_nano_machine UUID;
  v_tag_overgeared UUID;
  v_tag_tbate UUID;
  v_tag_mount_hua UUID;
  v_tag_solo_leveling UUID;
  v_tag_manhwa_market UUID;
  v_tag_sword_bitten UUID;
  v_tag_reaper UUID;
  v_tag_manhwa UUID;
  v_tag_adaptation UUID;
  v_tag_top_10 UUID;
  v_tag_completed UUID;
  v_tag_orv UUID;
  v_tag_anime UUID;
  v_tag_march_picks UUID;
BEGIN

  -- Fetch category IDs
  SELECT id INTO v_cat_axed_series FROM article_categories WHERE slug = 'axed-series';
  SELECT id INTO v_cat_industry_commentary FROM article_categories WHERE slug = 'industry-commentary';
  SELECT id INTO v_cat_editorials FROM article_categories WHERE slug = 'editorials';
  SELECT id INTO v_cat_recommendations FROM article_categories WHERE slug = 'recommendations';
  SELECT id INTO v_cat_release_announcements FROM article_categories WHERE slug = 'release-announcements';
  SELECT id INTO v_cat_hiatus_news FROM article_categories WHERE slug = 'hiatus-news';

  -- Insert tags (idempotent)
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Tower of God', 'tower-of-god') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_tower_of_god FROM article_tags WHERE slug = 'tower-of-god';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Kakao Webtoon', 'kakao') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_kakao FROM article_tags WHERE slug = 'kakao';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Murim Login', 'murim-login') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_murim_login FROM article_tags WHERE slug = 'murim-login';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Regression Fantasy', 'regression-fantasy') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_regression_fantasy FROM article_tags WHERE slug = 'regression-fantasy';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Nano Machine', 'nano-machine') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_nano_machine FROM article_tags WHERE slug = 'nano-machine';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Overgeared', 'overgeared') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_overgeared FROM article_tags WHERE slug = 'overgeared';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'TBATE', 'tbate') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_tbate FROM article_tags WHERE slug = 'tbate';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Return of Mount Hua', 'mount-hua') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_mount_hua FROM article_tags WHERE slug = 'mount-hua';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Solo Leveling', 'solo-leveling') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_solo_leveling FROM article_tags WHERE slug = 'solo-leveling';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Market', 'manhwa-market') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_manhwa_market FROM article_tags WHERE slug = 'manhwa-market';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Axed', 'sword-bitten') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_sword_bitten FROM article_tags WHERE slug = 'sword-bitten';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Reaper of the Drifting Moon', 'reaper') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_reaper FROM article_tags WHERE slug = 'reaper';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Manhwa', 'manhwa') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_manhwa FROM article_tags WHERE slug = 'manhwa';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Adaptation', 'adaptation') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_adaptation FROM article_tags WHERE slug = 'adaptation';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Top 10', 'top-10') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_top_10 FROM article_tags WHERE slug = 'top-10';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Completed', 'completed') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_completed FROM article_tags WHERE slug = 'completed';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Omniscient Reader', 'orv') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_orv FROM article_tags WHERE slug = 'orv';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Anime', 'anime') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_anime FROM article_tags WHERE slug = 'anime';
  INSERT INTO article_tags (id, name, slug) VALUES (gen_random_uuid(), 'Monthly Picks', 'march-picks') ON CONFLICT (slug) DO NOTHING;
  SELECT id INTO v_tag_march_picks FROM article_tags WHERE slug = 'march-picks';

  -- Insert base articles and media assets

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('48e61925-5800-4e75-ae7f-8300b1f84891', 'article-solo-leveling', 'article-image', md5('article-solo-leveling'), 1200, 675, 1.7778, 'image/webp', '#12082A', '', '[{"width":400,"format":"webp","url":"/images/articles/article-solo-leveling-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-solo-leveling-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-solo-leveling-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT 'e52bd9f2-a30c-4145-9a1b-845ef9945efa', 'solo-leveling-completed-10-years', $art$Solo Leveling Officially Completes After 10 Years$art$, $art$The manhwa that redefined the isekai genre has reached its final chapter$art$,
    $art$## The End of an Era

Solo Leveling has officially concluded after ten remarkable years. What began as a web novel adaptation became the most-read manhwa globally, fundamentally reshaping reader expectations for the medium.

## Legacy

The series introduced the iconic 'system' mechanic that dozens of titles have since emulated. Its anime adaptation by A-1 Pictures introduced millions of new readers to the manhwa format.

## What's Next

Author Chugong has hinted at a new project, though no details have been released.$art$, $art$After a decade-long run, Chugong's landmark manhwa Solo Leveling concludes, leaving a permanent mark on the global manhwa industry.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-solo-leveling' AND asset_type = 'article-image' LIMIT 1),
    v_cat_release_announcements, 'published', '2026-01-15T09:00:00Z', TRUE, 4, 320
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'solo-leveling-completed-10-years');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('e52bd9f2-a30c-4145-9a1b-845ef9945efa', v_tag_solo_leveling) ON CONFLICT DO NOTHING;
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('e52bd9f2-a30c-4145-9a1b-845ef9945efa', v_tag_manhwa) ON CONFLICT DO NOTHING;
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('e52bd9f2-a30c-4145-9a1b-845ef9945efa', v_tag_completed) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('2a7daa5c-2d21-4d0c-b4a2-86450e3c1abc', 'article-anime-adaptation', 'article-image', md5('article-anime-adaptation'), 1200, 675, 1.7778, 'image/webp', '#060E28', '', '[{"width":400,"format":"webp","url":"/images/articles/article-anime-adaptation-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-anime-adaptation-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-anime-adaptation-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT 'bcff8391-0a5f-4ef1-b9a9-f74ec34385dd', 'overgeared-anime-adaptation-announced', $art$Overgeared Gets Full Anime Adaptation$art$, $art$The beloved game-world manhwa is heading to animation$art$,
    $art$## Official Announcement

MAPPA has officially confirmed an anime adaptation of Park Saenal's Overgeared. The series, which follows legendary blacksmith Grid in a virtual reality MMORPG, has accumulated over 1,500 chapters.

## Production Details

The first season will adapt the early Reidan arc. A release window of late 2026 has been announced.

## Community Reaction

Fans have expressed excitement and some apprehension given the sheer volume of source material that needs to be adapted.$art$, $art$Studio MAPPA confirms a full anime adaptation of Overgeared, one of the longest-running and most beloved game-world manhwa series.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-anime-adaptation' AND asset_type = 'article-image' LIMIT 1),
    v_cat_release_announcements, 'published', '2026-02-01T10:00:00Z', TRUE, 3, 260
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'overgeared-anime-adaptation-announced');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('bcff8391-0a5f-4ef1-b9a9-f74ec34385dd', v_tag_overgeared) ON CONFLICT DO NOTHING;
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('bcff8391-0a5f-4ef1-b9a9-f74ec34385dd', v_tag_anime) ON CONFLICT DO NOTHING;
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('bcff8391-0a5f-4ef1-b9a9-f74ec34385dd', v_tag_adaptation) ON CONFLICT DO NOTHING;

  -- Insert variation articles

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('aa029abe-5ac6-4a59-9d3a-b1c004d5b47a', 'article-industry-news-v0', 'article-image', md5('article-industry-news-v0'), 1200, 675, 1.7778, 'image/webp', '#1C0808', '', '[{"width":400,"format":"webp","url":"/images/articles/article-industry-news-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-industry-news-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-industry-news-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '50f66af4-9364-47eb-b055-dc2d8ae6ec45', 'tower-of-god-news-1', $art$Tower of God Season 3 Release Date Confirmed$art$, 'Latest update from the manhwa world',
    $art$## Tower of God Season 3 Release Date Confirmed

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on tower of god season 3 release date confirmed — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-industry-news-v0' AND asset_type = 'article-image' LIMIT 1),
    v_cat_release_announcements, 'published', '2026-01-20T08:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'tower-of-god-news-1');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('50f66af4-9364-47eb-b055-dc2d8ae6ec45', v_tag_tower_of_god) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('9128ef0b-baa4-451c-b2e1-3e4a64914af4', 'article-anime-adaptation-v1', 'article-image', md5('article-anime-adaptation-v1'), 1200, 675, 1.7778, 'image/webp', '#060E28', '', '[{"width":400,"format":"webp","url":"/images/articles/article-anime-adaptation-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-anime-adaptation-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-anime-adaptation-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '78f82b2b-0f90-45b6-a826-584b132ce886', 'tbate-news-2', $art$The Beginning After the End Manga Adaptation Details$art$, 'Latest update from the manhwa world',
    $art$## The Beginning After the End Manga Adaptation Details

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on the beginning after the end manga adaptation details — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-anime-adaptation-v1' AND asset_type = 'article-image' LIMIT 1),
    v_cat_release_announcements, 'published', '2026-01-25T09:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'tbate-news-2');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('78f82b2b-0f90-45b6-a826-584b132ce886', v_tag_tbate) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('84e54213-41f1-4694-8bce-2d05ea999fc4', 'article-hiatus-return-v2', 'article-image', md5('article-hiatus-return-v2'), 1200, 675, 1.7778, 'image/webp', '#061818', '', '[{"width":400,"format":"webp","url":"/images/articles/article-hiatus-return-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-hiatus-return-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-hiatus-return-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '2d0f9e5b-284b-45ad-9957-6468d2b865ba', 'reaper-news-3', $art$Reaper of the Drifting Moon Enters Final Arc$art$, 'Latest update from the manhwa world',
    $art$## Reaper of the Drifting Moon Enters Final Arc

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on reaper of the drifting moon enters final arc — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-hiatus-return-v2' AND asset_type = 'article-image' LIMIT 1),
    v_cat_hiatus_news, 'published', '2026-02-03T10:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'reaper-news-3');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('2d0f9e5b-284b-45ad-9957-6468d2b865ba', v_tag_reaper) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('b700a6b8-df6d-478b-99ba-e0747ba8878b', 'article-industry-news-v3', 'article-image', md5('article-industry-news-v3'), 1200, 675, 1.7778, 'image/webp', '#1C0808', '', '[{"width":400,"format":"webp","url":"/images/articles/article-industry-news-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-industry-news-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-industry-news-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '72064b16-0f01-497c-b994-0a252a8d3f19', 'orv-news-4', $art$Omniscient Reader's Viewpoint Drama Announced$art$, 'Latest update from the manhwa world',
    $art$## Omniscient Reader's Viewpoint Drama Announced

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on omniscient reader's viewpoint drama announced — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-industry-news-v3' AND asset_type = 'article-image' LIMIT 1),
    v_cat_release_announcements, 'published', '2026-02-10T09:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'orv-news-4');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('72064b16-0f01-497c-b994-0a252a8d3f19', v_tag_orv) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('2aeb0e6a-57bf-42e4-a89b-3bea3365e225', 'article-manhwa-market-v4', 'article-image', md5('article-manhwa-market-v4'), 1200, 675, 1.7778, 'image/webp', '#080E1C', '', '[{"width":400,"format":"webp","url":"/images/articles/article-manhwa-market-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-manhwa-market-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-manhwa-market-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT 'e72faecb-6134-4a1e-9798-cd920a944d9b', 'manhwa-market-news-5', $art$Why Manhwa is Outselling Manga in 2026$art$, 'Latest update from the manhwa world',
    $art$## Why Manhwa is Outselling Manga in 2026

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on why manhwa is outselling manga in 2026 — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-manhwa-market-v4' AND asset_type = 'article-image' LIMIT 1),
    v_cat_industry_commentary, 'published', '2026-02-14T11:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'manhwa-market-news-5');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('e72faecb-6134-4a1e-9798-cd920a944d9b', v_tag_manhwa_market) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('1a14c41a-07ce-4fdd-bc17-4c33c0e01b99', 'article-anime-adaptation-v5', 'article-image', md5('article-anime-adaptation-v5'), 1200, 675, 1.7778, 'image/webp', '#060E28', '', '[{"width":400,"format":"webp","url":"/images/articles/article-anime-adaptation-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-anime-adaptation-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-anime-adaptation-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT 'b57126ef-dc54-4e6c-9653-21bd2e8b979b', 'nano-machine-news-6', $art$Nano Machine Gets Anime Green Light$art$, 'Latest update from the manhwa world',
    $art$## Nano Machine Gets Anime Green Light

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on nano machine gets anime green light — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-anime-adaptation-v5' AND asset_type = 'article-image' LIMIT 1),
    v_cat_release_announcements, 'published', '2026-02-18T10:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'nano-machine-news-6');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('b57126ef-dc54-4e6c-9653-21bd2e8b979b', v_tag_nano_machine) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('1c6cdac9-ce60-4025-a46d-e4e6611d6cd5', 'article-hiatus-return-v6', 'article-image', md5('article-hiatus-return-v6'), 1200, 675, 1.7778, 'image/webp', '#061818', '', '[{"width":400,"format":"webp","url":"/images/articles/article-hiatus-return-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-hiatus-return-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-hiatus-return-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '93dfe8ff-d424-433d-9b9c-d4f1f386a966', 'mount-hua-news-7', $art$Return of the Mount Hua Sect Hiatus Update$art$, 'Latest update from the manhwa world',
    $art$## Return of the Mount Hua Sect Hiatus Update

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on return of the mount hua sect hiatus update — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-hiatus-return-v6' AND asset_type = 'article-image' LIMIT 1),
    v_cat_hiatus_news, 'published', '2026-02-22T09:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'mount-hua-news-7');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('93dfe8ff-d424-433d-9b9c-d4f1f386a966', v_tag_mount_hua) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('24326098-4637-4423-a55c-5cbcfc3637c1', 'article-recommendations-v7', 'article-image', md5('article-recommendations-v7'), 1200, 675, 1.7778, 'image/webp', '#100820', '', '[{"width":400,"format":"webp","url":"/images/articles/article-recommendations-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-recommendations-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-recommendations-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '8f27015f-8508-4ed2-bef3-c11ff802e337', 'top-10-news-8', $art$Top 10 Manhwa to Read in 2026$art$, 'Latest update from the manhwa world',
    $art$## Top 10 Manhwa to Read in 2026

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on top 10 manhwa to read in 2026 — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-recommendations-v7' AND asset_type = 'article-image' LIMIT 1),
    v_cat_recommendations, 'published', '2026-03-01T08:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'top-10-news-8');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('8f27015f-8508-4ed2-bef3-c11ff802e337', v_tag_top_10) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('0d6231a3-c805-4ed0-ab4e-b1c1e03819c7', 'article-editorial-opinion-v8', 'article-image', md5('article-editorial-opinion-v8'), 1200, 675, 1.7778, 'image/webp', '#0E0A1E', '', '[{"width":400,"format":"webp","url":"/images/articles/article-editorial-opinion-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-editorial-opinion-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-editorial-opinion-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT 'dfdd1d42-9c6d-46e6-aa68-c50fa86f4bda', 'regression-fantasy-news-9', $art$The Rise of Regression Fantasy in Korean Webtoons$art$, 'Latest update from the manhwa world',
    $art$## The Rise of Regression Fantasy in Korean Webtoons

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on the rise of regression fantasy in korean webtoons — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-editorial-opinion-v8' AND asset_type = 'article-image' LIMIT 1),
    v_cat_editorials, 'published', '2026-03-05T10:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'regression-fantasy-news-9');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('dfdd1d42-9c6d-46e6-aa68-c50fa86f4bda', v_tag_regression_fantasy) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('9be3d9fa-9747-42f6-bb69-0908cf5476ab', 'article-axed-series-v9', 'article-image', md5('article-axed-series-v9'), 1200, 675, 1.7778, 'image/webp', '#140606', '', '[{"width":400,"format":"webp","url":"/images/articles/article-axed-series-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-axed-series-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-axed-series-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT 'ed997605-8c8b-4b4d-baba-5ca38f272a6c', 'sword-bitten-news-10', $art$Sword Bitten Axed After Low Engagement$art$, 'Latest update from the manhwa world',
    $art$## Sword Bitten Axed After Low Engagement

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on sword bitten axed after low engagement — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-axed-series-v9' AND asset_type = 'article-image' LIMIT 1),
    v_cat_axed_series, 'published', '2026-03-10T09:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'sword-bitten-news-10');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('ed997605-8c8b-4b4d-baba-5ca38f272a6c', v_tag_sword_bitten) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('3e49c2cc-0efe-4be6-9931-ea8438dd687d', 'article-manhwa-market-v10', 'article-image', md5('article-manhwa-market-v10'), 1200, 675, 1.7778, 'image/webp', '#080E1C', '', '[{"width":400,"format":"webp","url":"/images/articles/article-manhwa-market-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-manhwa-market-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-manhwa-market-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT 'd85771ee-3cbf-4fad-8801-5d976397a6b1', 'kakao-news-11', $art$Kakao Webtoon Announces Global Expansion$art$, 'Latest update from the manhwa world',
    $art$## Kakao Webtoon Announces Global Expansion

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on kakao webtoon announces global expansion — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-manhwa-market-v10' AND asset_type = 'article-image' LIMIT 1),
    v_cat_industry_commentary, 'published', '2026-03-15T11:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'kakao-news-11');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('d85771ee-3cbf-4fad-8801-5d976397a6b1', v_tag_kakao) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('bc515426-b7ec-4b23-8281-f8cb94b2d4d4', 'article-recommendations-v11', 'article-image', md5('article-recommendations-v11'), 1200, 675, 1.7778, 'image/webp', '#100820', '', '[{"width":400,"format":"webp","url":"/images/articles/article-recommendations-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-recommendations-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-recommendations-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '5a0f3dfa-d669-460c-8615-0e2849542c2d', 'march-picks-news-12', $art$Best New Manhwa Releases: March 2026$art$, 'Latest update from the manhwa world',
    $art$## Best New Manhwa Releases: March 2026

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on best new manhwa releases: march 2026 — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-recommendations-v11' AND asset_type = 'article-image' LIMIT 1),
    v_cat_recommendations, 'published', '2026-03-20T08:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'march-picks-news-12');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('5a0f3dfa-d669-460c-8615-0e2849542c2d', v_tag_march_picks) ON CONFLICT DO NOTHING;

  INSERT INTO media_assets (id, slug, asset_type, content_hash, original_width, original_height, aspect_ratio, mime_type, dominant_color, blur_data_uri, variants, r2_base_path)
  VALUES ('2d9b6ed9-ac3a-41a4-8979-cde83875c89a', 'article-anime-adaptation-v12', 'article-image', md5('article-anime-adaptation-v12'), 1200, 675, 1.7778, 'image/webp', '#060E28', '', '[{"width":400,"format":"webp","url":"/images/articles/article-anime-adaptation-400w.webp","size":22500},{"width":800,"format":"webp","url":"/images/articles/article-anime-adaptation-800w.webp","size":90000},{"width":1200,"format":"webp","url":"/images/articles/article-anime-adaptation-1200w.webp","size":202500}]', '/images/articles')
  ON CONFLICT (slug, asset_type, content_hash) DO NOTHING;

  INSERT INTO articles (id, slug, title, subtitle, body, excerpt, featured_image_id, category_id, publication_state, publish_date, featured, reading_time_minutes, word_count)
  SELECT '211b8c1a-3664-428b-a9d4-1e1c0469ac9b', 'murim-login-news-13', $art$Murim Login Season 2 Confirmed$art$, 'Latest update from the manhwa world',
    $art$## Murim Login Season 2 Confirmed

This is developing news from the manhwa and webtoon industry. We will continue to update this article as more information becomes available.

## Background

The community has been closely following this story. Reactions have been mixed but largely enthusiastic.

## What This Means

For fans of the genre, this represents a significant development in an already exciting year for manhwa.$art$, $art$Latest update on murim login season 2 confirmed — stay tuned for more details as they emerge from the source.$art$,
    (SELECT id FROM media_assets WHERE slug = 'article-anime-adaptation-v12' AND asset_type = 'article-image' LIMIT 1),
    v_cat_release_announcements, 'published', '2026-03-25T09:00:00Z', FALSE, 2, 60
  WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'murim-login-news-13');
  INSERT INTO article_tag_assignments (article_id, tag_id) VALUES ('211b8c1a-3664-428b-a9d4-1e1c0469ac9b', v_tag_murim_login) ON CONFLICT DO NOTHING;

END $$;
